#
# https://travis-ci.org configuration file for cherish
#

language: cpp

os:
  - linux

compiler: 
  - gcc

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

branches:
  only:
    - master
    - develop

env:
  - CHERISH_SRC=${TRAVIS_BUILD_DIR}/src
  - CHERISH_BUILD=${TRAVIS_BUILD_DIR}/build

before_install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq update

install:
  - sudo apt-get --yes install g++-4.8 qt55base qt55imageformats qt55svg 
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  #  - sudo apt-get -y install qt55[QPACKAGE]


before_script:
  - QTDIR="/opt/qt55"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt55/bin/qt55-env.sh
  - mkdir $CHERISH_BUILD
  - cd $CHERISH_BUILD
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt55/lib/cmake -DCherish_BUILD_TEST=ON . $CHERISH_SOURCE

script:
  - make -j 3


#notifications:
#  email:
#    - vicrucann@gmail.com

