language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

branches:
  only:
    - master
    - develop

env:
  - CHERISH_SRC=${TRAVIS_BUILD_DIR}/src
  - CHERISH_BUILD=${TRAVIS_BUILD_DIR}/build

before_install:
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq update
  - wget https://github.com/vicrucann/OpenSceneGraph/releases/download/OpenSceneGraph-3.4.0/osg-340-deb.tar.gz
  - tar -zxvf osg-340-deb.tar.gz

install:
  - sudo apt-get --yes install qt55base qt55imageformats qt55svg 
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  #  - sudo apt-get -y install qt55[QPACKAGE]a
  - sudo cp -rv osg-340-deb/lib64 /usr/local/
  - sudo cp -rv osg-340-deb/include /usr/local/
  - sudo cp -rv osg-340-deb/bin /usr/local/


before_script:
  # Qt location
  - QTDIR="/opt/qt55"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt55/bin/qt55-env.sh
  # OpenSceneGraph download
  - export LD_LIBRARY_PATH="/usr/local/lib64:/usr/local/lib:$LD_LIBRARY_PATH"
  - export OPENTHREADS_INC_DIR="/usr/local/include"
  - export OPENTHREADS_LIB_DIR="/usr/local/lib64:/usr/local/lib"
  - export PATH="$OPENTHREADS_LIB_DIR:$PATH"
  # cmake command
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt54/lib/cmake -DCherish_BUILD_TEST=ON . $CHERISH_SOURCE

script:
  - make


#notifications:
#  email:
#    - vicrucann@gmail.com

