---

port: 4000
host: localhost
safe: true


### site serving configuration ###
baseurl: https://vicrucann.github.io/cherish
exclude: [CNAME, README.md, .gitignore]
#permalink: / ## disables post output
timezone: null
lsi: false

### content configuration ###
title:       "cherISh: Cultural Heritage data representations by Image manipulation and 3D sketching "
keywords:    "archaeology, cultural heritage, 3D reconstruction, virtual tour, 3D sketching"
description: "Software package for cultural heritage sparse data gather-together and building a 3D representation of the historical site"
source_link: "https://github.com/vicrucann/dura-europos-insitu"
favicon:     "assets/images/favicon.ico"
touch_icon:  "assets/images/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'


### file locations
source:      .
destination: ./_site
